### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [saitjr/STLoadingGroup#3]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by saitjr** [comment]
Working on it 💪.

**Comment by saitjr** [comment]
Swift3 available!

**Comment by lfarah** [comment]
Thanks, @saitjr 🎉

**Comment by saitjr** [comment]
Project is not stable yet. Still working.
